{
 "title": "Proof Server",
 "description": "Proof server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Proof Requests Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "proof_server_proof_request_count_total",
     "legendFormat": "Proof Server"
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "proof_server_eth_balance_ETH",
     "legendFormat": "Proof Server: {{proof_server_address}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "proof_server_process_memory_usage_MB",
     "legendFormat": "Proof Server"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "proof_server_process_cpu_usage_percent",
     "legendFormat": "Proof Server"
    }
   ]
  },
  {
   "title": "Total Disc Write Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "proof_server_process_disk_space_usage_MB",
     "legendFormat": "Proof Server"
    }
   ]
  }
 ]
}